//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booksInfo
    {
        public int id { get; set; }
        public string books_name { get; set; }
        public string books_author_name { get; set; }
        public Nullable<System.DateTime> books_publication_date { get; set; }
        public Nullable<decimal> books_price { get; set; }
        public Nullable<int> books_quantity { get; set; }
    }
}
