//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerissue
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public string customer_surname { get; set; }
        public string Customer_email { get; set; }
        public string customer_phone { get; set; }
        public string book_name { get; set; }
        public Nullable<System.DateTime> book_issue_date { get; set; }
        public Nullable<int> book_price { get; set; }
        public string customer_enrollment_no { get; internal set; }
    }
}
