//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class librarymanagmentEntities1 : DbContext
    {
        public librarymanagmentEntities1()
            : base("name=librarymanagmentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookmaster> bookmasters { get; set; }
        public virtual DbSet<membermaster> membermasters { get; set; }
        public virtual DbSet<planmaster> planmasters { get; set; }
        public virtual DbSet<profilemaster> profilemasters { get; set; }
        public virtual DbSet<profileuser> profileusers { get; set; }
        public virtual DbSet<purchasemain> purchasemains { get; set; }
        public virtual DbSet<purchasesub> purchasesubs { get; set; }
        public virtual DbSet<registerbook> registerbooks { get; set; }
        public virtual DbSet<rolemaster> rolemasters { get; set; }
        public virtual DbSet<stack> stacks { get; set; }
    }
}
