//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmaster
    {
        public int id { get; set; }
        public string name { get; set; }
        public string doc { get; set; }
        public Nullable<int> booklimit { get; set; }
        public Nullable<int> bookvalidity { get; set; }
        public Nullable<int> amount { get; set; }
        public string diss { get; set; }
        public string status { get; set; }
    }
}
