//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace librarymanagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stack()
        {
            this.purchasesubs = new HashSet<purchasesub>();
        }
    
        public int id { get; set; }
        public Nullable<int> bookid { get; set; }
        public string bookname { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchasesub> purchasesubs { get; set; }
    }
}
